# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d0ad49957c7c2ad5ac9f82376eb892476369fdb2bbd791fa239698894ce8278cf683ac81411b37cd3dc6c452343add2be11871d3220629e0e1f05ad7bf052b

test:
  secret_key_base: 11cae842ad262c1f5f87b3d6ba1bd73103642228ee9a56a944054c7b825f81c42e13774d5ca73e73304ec1a47aefd467d46ead9e7c90660e1839581380484853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
